staff-review:

  minimum-playtime-hours: 7

  cooldown-hours: 24

  minimum-comment-length: 10

  maximum-comment-length: 250

suggestion:

  minimum-length: 10

  maximum-length: 300

bug-report:

  minimum-length: 10

  maximum-length: 300